# File: .github/workflows/template-sync.yml
name: actions-template-sync

on:
  push:
    # cronjob trigger
  schedule:
  - cron:  "0 0 * * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        # https://github.com/actions/checkout#usage
        # uncomment if you use submodules within the repository
        # with:
        #   submodules: true

      - name: actions-template-sync
        id: sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          source_repo_path: ScoopInstaller/BucketTemplate
          upstream_branch: master # defaults to main
          is_force_push_pr: true
          # pr_labels: <label1>,<label2>[,...] # defaults to template_sync
  
      - name: print output
        env:
          FORMER_OUTPUT_PR_BRANCH: ${{ steps.sync.outputs.pr_branch }}
        run: echo "pr_branch ${FORMER_OUTPUT_PR_BRANCH}"
